### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by andyjessen** [MIDRC/Stanford_Penn_MIDRC_Deidentifier#3]
I am receiving a not subscriptable error after running the following script. I have tried with multiple small lists and can't get beyond this. Can you suggest a route to try?

`python main.py --input_file_path input_string_array.npy --output_file_path output_string_array.npy --device_list cpu`

> Traceback (most recent call last):
  File "...\.conda\envs\stanford-deidentifier\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "...\.conda\envs\stanford-deidentifier\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "...\Stanford_Penn_MIDRC_Deidentifier\main.py", line 89, in deidentifier_model_and
_hide_in_plain_sight
    deidentifier_model(
  File "...\Stanford_Penn_MIDRC_Deidentifier\deidentifier_model.py", line 80, in deidenti
fier_model
    int(classifier.preprocess(break_token)["input_ids"][0][1])
TypeError: 'generator' object is not subscriptable

**Comment by andyjessen** [comment]
I am creating the sample string to be identified as follows.

```
import numpy as np
string_array=["We used the system MedClinical data transmitter and sent the data on 2/1/2020, under the ID 5874233. We received the confirmation of Dr Perez. He is reachable at 567-493-1234."]
np_array=np.array(string_array)
np.save("input_string_array.npy", np_array)
```

**Comment by kswanjitsu** [comment]
I ran into same issue and just saw you post this. I'll update here if I find a fix. Not sure how active the repo is.

**Comment by kswanjitsu** [comment]
Okay, so the generator issue is from dependency breaking changes, and I do not have time to refactor this code base, there is a lot to bring up to speed with the deps. README is unclear, but I think they had to have used ~python=3.8, anything above or below this would not allow for deps to install.

So reconfigure your env to use python 3.8 in conda, mamba, pip virtual env, whatever. Then just pip install -r requirement.txt and run according the remainder of their docs. Got it working! And it works great!

**Comment by andyjessen** [comment]
Thank you @kswanjitsu! This suggestion (python=3.8) solved the issue. Appreciate it.
